# Generated by Django 5.2 on 2025-06-12 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenciaUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_licencia', models.CharField(max_length=100)),
                ('uso_licencia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Licencia de Uso',
                'verbose_name_plural': 'Licencias de Uso',
            },
        ),
        migrations.CreateModel(
            name='ResponsableObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cip_cap', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Responsable de Obra',
                'verbose_name_plural': 'Responsables de Obra',
            },
        ),
        migrations.CreateModel(
            name='Zonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonificacion', models.CharField(max_length=15)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Zonificación',
                'verbose_name_plural': 'Zonificaciones',
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_resolucion', models.CharField(max_length=50, unique=True, verbose_name='N° Resolución')),
                ('num_expediente', models.CharField(max_length=50, unique=True, verbose_name='N° Expediente')),
                ('num_recibo', models.CharField(blank=True, max_length=50, verbose_name='N° Recibo')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('administrado', models.CharField(max_length=100)),
                ('propietario', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=300)),
                ('calle', models.CharField(max_length=200)),
                ('nombre_licencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resoluciones.licenciauso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areatechada_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalle_areatechada', models.TextField()),
                ('num_pisos', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_sotano', models.IntegerField(default=0)),
                ('semisotano', models.BooleanField(default=False)),
                ('resolucion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resoluciones.resolucion')),
                ('responsable_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resoluciones.responsableobra')),
                ('zonificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.zonificacion')),
            ],
            options={
                'verbose_name': 'Detalle de Resolución',
                'verbose_name_plural': 'Detalles de Resoluciones',
            },
        ),
    ]
