# Generated by Django 5.2 on 2025-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
