# Generated by Django 5.2 on 2025-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0002_zonificacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
