# Generated by Django 5.2 on 2025-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0003_alter_zonificacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleresolucion',
            name='detalle_areatechada',
            field=models.TextField(default='-'),
        ),
    ]
