# Generated by Django 5.2 on 2025-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0004_alter_detalleresolucion_detalle_areatechada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleresolucion',
            name='altura',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='calle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='direccion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
