# Generated by Django 5.2 on 2025-07-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0005_alter_detalleresolucion_altura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cip_cap', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Supervisor de Obra',
                'verbose_name_plural': 'Supervisores de Obra',
            },
        ),
        migrations.AlterField(
            model_name='responsableobra',
            name='cip_cap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='responsableobra',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='detalleresolucion',
            name='supervisor_obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='resoluciones.supervisorobra'),
            preserve_default=False,
        ),
    ]
