# Generated by Django 5.2 on 2025-07-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0006_supervisorobra_alter_responsableobra_cip_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleresolucion',
            name='azotea',
            field=models.BooleanField(default=False),
        ),
    ]
