# Generated by Django 5.2 on 2025-07-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0007_detalleresolucion_azotea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleresolucion',
            name='detalle_areatechada',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='detalleresolucion',
            name='zonificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.zonificacion'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
