# Generated by Django 5.2 on 2025-07-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0008_alter_detalleresolucion_detalle_areatechada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleresolucion',
            name='supervisor_obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resoluciones.supervisorobra'),
        ),
    ]
